# Generated by Django 4.1.7 on 2023-05-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
